version: '3.8'

volumes:
  mongodb_data: { driver: local }

services:

  traefik:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      --api.insecure=true --providers.docker
      --entrypoints.service2020.address=:2020
    ports:
      # The HTTP port
      - "81:80"
      - "2020:2020"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  # rocketchat:
  #   image: registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest}
  #   restart: always
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.rocketchat.rule: Host(`${DOMAIN:-}`)
  #     traefik.http.routers.rocketchat.tls: "true"
  #     traefik.http.routers.rocketchat.entrypoints: https
  #     traefik.http.routers.rocketchat.tls.certresolver: le
  #   environment:
  #     MONGO_URL: "${MONGO_URL:-\
  #       mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
  #       ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
  #     MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
  #       -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
  #       local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
  #     ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
  #     PORT: ${PORT:-3000}
  #     DEPLOY_METHOD: docker
  #     DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
  #     REG_TOKEN: ${REG_TOKEN:-}
  #   depends_on:
  #     - mongodb
  #   expose:
  #     - ${PORT:-3000}
  #   ports:
  #     - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"

  # mongodb:
  #   image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-6.0}
  #   restart: always
  #   volumes:
  #     - mongodb_data:/bitnami/mongodb
  #   environment:
  #     MONGODB_REPLICA_SET_MODE: primary
  #     MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
  #     MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
  #     MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
  #     MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
  #     MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
  #     MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
  #     ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}


  zitadel:
    restart: 'always'
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.zitadel.rule=HostSNI(`*`)" # Match all hostnames
      - "traefik.tcp.routers.zitadel.entrypoints=service2020"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080" # Service port
      - "traefik.http.middlewares.change-host.headers.customrequestheaders.Host=zitadel"
      - "traefik.http.routers.zitadel.middlewares=change-host"

    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=db'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      db:
        condition: 'service_healthy'
    expose:
      - 8080

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zitadel
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
